site_name: LiebmausNet
site_url: https://www.liebmaus.net
copyright: >
  &copy; 2024 All rights reserved.
nav:
  - Home: "index.md"
  - LiebmausBot:
    - bot/index.md
    - Basic Commands: bot/basic-commands.md
    - Randomizers:
      - Lord of the Rings quotes: bot/randomizers/lotr-quotes.md
theme:
  name: material
  logo: images/suessmaus.png
  favicon: images/suessmaus.png
  palette:
    scheme: slate
  features:
    # QOL features
    - search.suggest
    - search.share
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.expand
    - toc.follow
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
markdown_extensions:
  - toc:
      permalink: true
plugins:
  - search
# Footer
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/LiebmausBot"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/LiebmausBot"
